const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const PORT=Number(process.env.PORT||3000),ROOT=__dirname,DIR=process.env.SKL_DATA_DIR||path.join(ROOT,'.data'),FILE=path.join(DIR,'db.json');
fs.mkdirSync(DIR,{recursive:true});const id=p=>p+'_'+crypto.randomBytes(7).toString('hex'),now=()=>new Date().toISOString();
const seed=()=>({users:[],sessions:[],clubs:[],players:[],leagues:[],members:[],fixtures:[],matches:[],events:[],friends:[],notifications:[],transactions:[],training:[]});
let db=fs.existsSync(FILE)?JSON.parse(fs.readFileSync(FILE,'utf8')):seed();const save=()=>{const t=FILE+'.tmp';fs.writeFileSync(t,JSON.stringify(db));fs.renameSync(t,FILE)};
const send=(res,s,d)=>{res.writeHead(s,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(d))};
const read=req=>new Promise((ok,no)=>{let b='';req.on('data',x=>b+=x);req.on('end',()=>{try{ok(b?JSON.parse(b):{})}catch(e){no(new Error('invalid_json'))}})});
const auth=req=>{const h=(req.headers.authorization||'').replace('Bearer ','');const s=db.sessions.find(x=>x.token===h&&Date.parse(x.expiresAt)>Date.now());return s&&db.users.find(u=>u.id===s.userId)};
const clean=u=>({id:u.id,username:u.username,displayName:u.displayName,clubId:u.clubId||null,avatar:u.avatar||'',createdAt:u.createdAt});
const club=x=>db.clubs.find(c=>c.id===x),player=x=>db.players.find(p=>p.id===x);
const notify=(userId,type,title,message,meta={})=>db.notifications.unshift({id:id('note'),userId,type,title,message,meta,read:false,createdAt:now()});
const names=['Omar','Youssef','Adam','Karim','Ziad','Mina','Ali','Hassan','Nour','Seif','Malek','Tarek','Amr','Fares','Khaled','Mahmoud','Ibrahim','Mostafa'],surnames=['Hassan','Khalil','Saber','Nabil','Fathy','Adel','Samir','Farouk','Salem','Mansour','Younes','Hegazy'];
function newClub(name,bot=false){const c={id:id('club'),name,crest:name.split(' ').map(x=>x[0]).join('').slice(0,3).toUpperCase(),bot,budget:1500000,wageBudget:120000,formation:'2-1-1',matchPlan:null,playerIds:[]};db.clubs.push(c);['GK','DEF','DEF','MID','MID','FWD','FWD','DEF'].forEach(pos=>{const o=62+Math.floor(Math.random()*22),p={id:id('pl'),clubId:c.id,name:names[Math.floor(Math.random()*names.length)]+' '+surnames[Math.floor(Math.random()*surnames.length)],position:pos,overall:o,fitness:85+Math.floor(Math.random()*16),form:60+Math.floor(Math.random()*31),fatigue:0,shooting:50+Math.floor(Math.random()*41),passing:50+Math.floor(Math.random()*41),defending:50+Math.floor(Math.random()*41),marketValue:50000+o*3500};db.players.push(p);c.playerIds.push(p.id)});return c}
function plan(c,p){let ids=p?.startingXI;if(!Array.isArray(ids)||ids.length!==5)ids=db.players.filter(x=>x.clubId===c.id).sort((a,b)=>b.overall-a.overall).slice(0,5).map(x=>x.id);const ps=ids.map(player);if(ps.length!==5||ps.some(x=>!x||x.clubId!==c.id)||!ps.some(x=>x.position==='GK'))throw new Error('A valid 5-player lineup with goalkeeper is required');return{startingXI:ids,formation:p?.formation||c.formation,tactics:p?.tactics||{mentality:'Balanced',pressing:50,passing:50,line:50}}}
function makeFixtures(l){const ids=db.members.filter(m=>m.leagueId===l.id).map(m=>m.clubId),a=ids.slice(),out=[];for(let r=0;r<ids.length-1;r++){for(let i=0;i<ids.length/2;i++){let x=a[i],y=a[ids.length-1-i];if(x&&y)out.push({id:id('fix'),leagueId:l.id,matchday:r+1,homeClubId:r%2?y:x,awayClubId:r%2?x:y,status:'scheduled',homeScore:null,awayScore:null,matchId:null,openAt:now(),deadline:new Date(Date.now()+1800000).toISOString()})}a.splice(1,0,a.pop())}const first=out.slice();for(const f of first)out.push({...f,id:id('fix'),matchday:f.matchday+ids.length-1,homeClubId:f.awayClubId,awayClubId:f.homeClubId});db.fixtures.push(...out);l.currentMatchday=1;l.totalMatchdays=(ids.length-1)*2;l.status='active'}
function start(f){const h=club(f.homeClubId),a=club(f.awayClubId),m={id:id('match'),fixtureId:f.id,leagueId:f.leagueId,homeClubId:h.id,awayClubId:a.id,minute:0,status:'live',phase:'first_half',homeScore:0,awayScore:0,possession:50,homePlan:plan(h,h.matchPlan),awayPlan:plan(a,a.matchPlan),homeStats:{shots:0,onTarget:0,saves:0,passes:0,tackles:0},awayStats:{shots:0,onTarget:0,saves:0,passes:0,tackles:0},updatedAt:now()};db.matches.push(m);f.status='live';f.matchId=m.id;save();return m}
function event(m,type,cid,pid,text){db.events.push({id:id('evt'),matchId:m.id,type,clubId:cid||null,playerId:pid||null,minute:m.minute,text,createdAt:now()})}
function tick(m){if(m.status!=='live')return;m.minute++;const h=club(m.homeClubId),a=club(m.awayClubId),hp=m.homePlan.tactics,ap=m.awayPlan.tactics,hs=db.players.filter(p=>h.playerIds.includes(p.id)).reduce((s,p)=>s+p.overall,0)/8,as=db.players.filter(p=>a.playerIds.includes(p.id)).reduce((s,p)=>s+p.overall,0)/8;m.possession=Math.max(20,Math.min(80,Math.round(50+(hp.passing-ap.passing)*.18+(hs-as)*.15)));m.homeStats.passes+=3+Math.floor(Math.random()*7);m.awayStats.passes+=3+Math.floor(Math.random()*7);for(const side of ['home','away']){const own=side==='home'?h:a,opp=side==='home'?a:h,pl=side==='home'?m.homePlan:m.awayPlan,st=side==='home'?m.homeStats:m.awayStats,other=side==='home'?ap:hp,ch=.055+(hs-as)*(side==='home'?.001:-.001)+(pl.tactics.pressing-other.pressing)*.0004;if(Math.random()<Math.max(.02,Math.min(.28,ch))){st.shots++;const shooters=pl.startingXI.map(player).filter(x=>x&&x.position!=='GK'),p=shooters[Math.floor(Math.random()*shooters.length)]||player(pl.startingXI[0]);const gk=player((side==='home'?m.awayPlan:m.homePlan).startingXI.map(player).find(x=>x?.position==='GK')?.id);if(Math.random()<.34+(p?.shooting||60)/500-(gk?.overall||65)/600){side==='home'?m.homeScore++:m.awayScore++;st.onTarget++;event(m,'goal',own.id,p?.id,own.name+' score!')}else if(Math.random()<.5){st.onTarget++;(side==='home'?m.awayStats:m.homeStats).saves++;event(m,'shot',own.id,p?.id,(p?.name||own.name)+' shoots — saved.')}}}if(m.minute===45){m.phase='halftime';event(m,'halftime',null,null,'Half-time.')}if(m.minute===46){m.phase='second_half';event(m,'kickoff',null,null,'Second half begins.')}if(m.minute===90){m.phase='stoppage';event(m,'stoppage',null,null,'Stoppage time.')}if(m.minute>=93){m.status='finished';m.phase='full_time';const f=db.fixtures.find(x=>x.id===m.fixtureId);if(f){f.status='played';f.homeScore=m.homeScore;f.awayScore=m.awayScore}event(m,'full_time',null,null,'Full-time: '+m.homeScore+'-'+m.awayScore);for(const cid of [m.homeClubId,m.awayClubId]){club(cid).budget+=5000;db.transactions.push({id:id('tx'),clubId:cid,type:'match_income',amount:5000,description:'Matchday income',matchId:m.id,createdAt:now()})}for(const p of [...m.homePlan.startingXI,...m.awayPlan.startingXI].map(player))if(p){p.fitness=Math.max(0,p.fitness-8);p.fatigue=Math.min(100,p.fatigue+12)}for(const u of db.users.filter(u=>u.clubId===h.id||u.clubId===a.id))notify(u.id,'match','Full time',h.name+' '+m.homeScore+'-'+m.awayScore+' '+a.name,{matchId:m.id})}m.updatedAt=now();save()}
setInterval(()=>db.matches.filter(x=>x.status==='live').forEach(tick),1000);
async function api(req,res){const p=new URL(req.url,'http://x').pathname;try{
if(req.method==='GET'&&p==='/api/health')return send(res,200,{ok:true,time:now()});
if(req.method==='POST'&&p==='/api/auth/signup'){const b=await read(req);if(!b.username||!b.password||b.password.length<6)throw Object.assign(new Error('username and password (6+ chars) required'),{status:400});if(db.users.some(u=>u.username.toLowerCase()===String(b.username).toLowerCase()))throw Object.assign(new Error('username already exists'),{status:409});const salt=crypto.randomBytes(16).toString('hex'),u={id:id('usr'),username:String(b.username).trim(),displayName:String(b.displayName||b.username).trim(),passwordSalt:salt,passwordHash:crypto.scryptSync(b.password,salt,64).toString('hex'),clubId:null,createdAt:now()};db.users.push(u);const t=id('sess');db.sessions.push({token:t,userId:u.id,expiresAt:new Date(Date.now()+2592e6).toISOString()});save();return send(res,201,{token:t,user:clean(u)})}
if(req.method==='POST'&&p==='/api/auth/login'){const b=await read(req),u=db.users.find(x=>x.username.toLowerCase()===String(b.username||'').toLowerCase());if(!u)throw Object.assign(new Error('invalid credentials'),{status:401});const h=crypto.scryptSync(String(b.password||''),u.passwordSalt,64).toString('hex');if(h!==u.passwordHash)throw Object.assign(new Error('invalid credentials'),{status:401});const t=id('sess');db.sessions.push({token:t,userId:u.id,expiresAt:new Date(Date.now()+2592e6).toISOString()});save();return send(res,200,{token:t,user:clean(u)})}
const u=auth(req);if(!u)throw Object.assign(new Error('unauthorized'),{status:401});
if(req.method==='GET'&&p==='/api/me')return send(res,200,{user:clean(u),club:u.clubId?club(u.clubId):null});
if(req.method==='POST'&&p==='/api/clubs'){if(u.clubId)throw Object.assign(new Error('club already exists'),{status:409});const b=await read(req),c=newClub(String(b.name||u.displayName+' FC'));u.clubId=c.id;save();return send(res,201,{club:c})}
if(req.method==='GET'&&p==='/api/players')return send(res,200,{players:db.players.filter(x=>x.clubId===u.clubId)});
if(req.method==='GET'&&p==='/api/friends')return send(res,200,{friends:db.friends.filter(f=>f.from===u.id||f.to===u.id).map(f=>({...f,otherUser:clean(db.users.find(x=>x.id===(f.from===u.id?f.to:f.from)))}))});
if(req.method==='POST'&&p==='/api/friends/request'){const b=await read(req),to=db.users.find(x=>x.username.toLowerCase()===String(b.username||'').toLowerCase());if(!to)throw Object.assign(new Error('user not found'),{status:404});const f={id:id('fr'),from:u.id,to:to.id,status:'pending',createdAt:now()};db.friends.push(f);notify(to.id,'friend','Friend request',u.displayName+' sent you a friend request.',{friendId:f.id});save();return send(res,201,{friend:f})}
if(req.method==='POST'&&p==='/api/friends/respond'){const b=await read(req),f=db.friends.find(x=>x.id===b.friendId&&x.to===u.id);if(!f)throw Object.assign(new Error('request not found'),{status:404});f.status=b.action==='accept'?'accepted':'rejected';save();return send(res,200,{friend:f})}
if(req.method==='GET'&&p==='/api/notifications')return send(res,200,{notifications:db.notifications.filter(n=>n.userId===u.id).slice(0,50)});
if(req.method==='POST'&&p==='/api/notifications/read'){const b=await read(req);db.notifications.filter(n=>n.userId===u.id&&(b.all||n.id===b.id)).forEach(n=>n.read=true);save();return send(res,200,{ok:true})}
if(req.method==='POST'&&p==='/api/leagues'){if(!u.clubId)throw Object.assign(new Error('create a club first'),{status:400});const b=await read(req),l={id:id('lg'),name:String(b.name||'Friends League').slice(0,40),ownerId:u.id,status:'preseason',maxTeams:18,currentMatchday:0,totalMatchdays:34,currentSeason:1,createdAt:now()};db.leagues.push(l);db.members.push({id:id('lm'),leagueId:l.id,userId:u.id,clubId:u.clubId,role:'owner'});save();return send(res,201,{league:l})}
if(req.method==='GET'&&p==='/api/leagues')return send(res,200,{leagues:db.members.filter(m=>m.userId===u.id).map(m=>db.leagues.find(l=>l.id===m.leagueId)).filter(Boolean)});
if(req.method==='POST'&&p==='/api/leagues/invite'){const b=await read(req),l=db.leagues.find(x=>x.id===b.leagueId),to=db.users.find(x=>x.username.toLowerCase()===String(b.username||'').toLowerCase());if(!l||l.ownerId!==u.id)throw Object.assign(new Error('league or permission error'),{status:403});if(!to)throw Object.assign(new Error('user not found'),{status:404});notify(to.id,'league','League invitation','You were invited to '+l.name,{leagueId:l.id});save();return send(res,200,{ok:true})}
if(req.method==='POST'&&p==='/api/leagues/accept'){const b=await read(req),l=db.leagues.find(x=>x.id===b.leagueId);if(!l)throw Object.assign(new Error('league not found'),{status:404});if(db.members.some(m=>m.leagueId===l.id&&m.userId===u.id))return send(res,200,{league:l});if(db.members.filter(m=>m.leagueId===l.id).length>=18)throw Object.assign(new Error('league full'),{status:409});db.members.push({id:id('lm'),leagueId:l.id,userId:u.id,clubId:u.clubId,role:'member'});save();return send(res,200,{league:l})}
if(req.method==='POST'&&p==='/api/leagues/start'){const b=await read(req),l=db.leagues.find(x=>x.id===b.leagueId);if(!l||l.ownerId!==u.id)throw Object.assign(new Error('league or permission error'),{status:403});let n=db.members.filter(m=>m.leagueId===l.id).length;while(n<18){const c=newClub(['Atlas FC','Cairo Kings','Nile United','Delta Stars','Alexandria SC','Pyramid City','Desert Lions','Red Falcons','Blue Waves','Capital FC','Royal Eagles','Port Said','Canal Athletic','Giza Sporting','Luxor FC','Aswan United','Sphinx FC','Pharaohs FC'][n],true);db.members.push({id:id('lm'),leagueId:l.id,userId:null,clubId:c.id,role:'bot'});n++}if(l.status!=='active')makeFixtures(l);save();return send(res,200,{league:l})}
if(req.method==='GET'&&p.startsWith('/api/leagues/')){const lid=p.split('/')[3],l=db.leagues.find(x=>x.id===lid);if(!l||!db.members.some(m=>m.leagueId===lid&&m.userId===u.id))throw Object.assign(new Error('forbidden'),{status:403});const table=db.members.filter(m=>m.leagueId===lid).map(m=>club(m.clubId)).map(c=>{const fs=db.fixtures.filter(f=>f.leagueId===lid&&f.status==='played'&&(f.homeClubId===c.id||f.awayClubId===c.id));let w=0,d=0,gf=0,ga=0;for(const f of fs){const home=f.homeClubId===c.id,a=home?f.homeScore:f.awayScore,b=home?f.awayScore:f.homeScore;gf+=a;ga+=b;if(a>b)w++;else if(a===b)d++}return{clubId:c.id,name:c.name,crest:c.crest,played:fs.length,wins:w,draws:d,losses:fs.length-w-d,gf,ga,gd:gf-ga,points:w*3+d}}).sort((a,b)=>b.points-a.points||b.gd-a.gd||b.gf-a.gf);const fx=db.fixtures.filter(f=>f.leagueId===lid&&f.matchday===l.currentMatchday).map(f=>({...f,home:club(f.homeClubId),away:club(f.awayClubId)}));return send(res,200,{league:l,standings:table,fixtures:fx})}
if(req.method==='GET'&&p==='/api/matchday'){const lid=new URL(req.url,'http://x').searchParams.get('leagueId'),l=db.leagues.find(x=>x.id===lid);if(!l)throw Object.assign(new Error('league not found'),{status:404});return send(res,200,{league:l,fixtures:db.fixtures.filter(f=>f.leagueId===lid&&f.matchday===l.currentMatchday).map(f=>({...f,home:club(f.homeClubId),away:club(f.awayClubId)})),serverTime:now()})}
if(req.method==='POST'&&p==='/api/matches/start'){const b=await read(req),f=db.fixtures.find(x=>x.id===b.fixtureId);if(!f||(f.homeClubId!==u.clubId&&f.awayClubId!==u.clubId))throw Object.assign(new Error('match not available'),{status:403});return send(res,200,{match:f.matchId?db.matches.find(x=>x.id===f.matchId):start(f)})}
if(req.method==='GET'&&p.startsWith('/api/matches/')){const m=db.matches.find(x=>x.id===p.split('/')[3]);if(!m)throw Object.assign(new Error('match not found'),{status:404});return send(res,200,{match:m,events:db.events.filter(e=>e.matchId===m.id),home:club(m.homeClubId),away:club(m.awayClubId),serverTime:now()})}
if(req.method==='POST'&&p==='/api/matches/plan'){const b=await read(req),c=club(u.clubId);c.matchPlan=plan(c,b.plan);c.formation=c.matchPlan.formation;save();return send(res,200,{plan:c.matchPlan})}
if(req.method==='POST'&&p==='/api/training'){const b=await read(req),type=b.type||'recovery';db.players.filter(x=>x.clubId===u.clubId).forEach(p=>{if(type==='recovery')p.fitness=Math.min(100,p.fitness+12);else if(type==='physical')p.fitness=Math.min(100,p.fitness+4);else p.form=Math.min(100,p.form+3)});db.training.push({id:id('tr'),clubId:u.clubId,type,createdAt:now()});save();return send(res,200,{ok:true})}
if(req.method==='GET'&&p==='/api/finance')return send(res,200,{balance:club(u.clubId)?.budget||0,transactions:db.transactions.filter(t=>t.clubId===u.clubId)});
throw Object.assign(new Error('not_found'),{status:404})}catch(e){send(res,e.status||500,{error:e.message||'server_error'})}}
http.createServer((req,res)=>{if(req.url.startsWith('/api/'))return api(req,res);const p=new URL(req.url,'http://x').pathname,file=p==='/'?'index.html':p.slice(1);if(!['index.html','styles.css','skl27.js'].includes(file))return send(res,404,{error:'not_found'});res.writeHead(200,{'Content-Type':file.endsWith('.html')?'text/html':file.endsWith('.css')?'text/css':'application/javascript'});res.end(fs.readFileSync(path.join(ROOT,file)))}).listen(PORT,()=>console.log('SKL27 on '+PORT));