const {useEffect,useState}=React;
const API='/api';
function App(){const [token,setToken]=useState(localStorage.sklToken||''),[screen,setScreen]=useState('home'),[user,setUser]=useState(null),[club,setClub]=useState(null),[players,setPlayers]=useState([]),[leagues,setLeagues]=useState([]),[league,setLeague]=useState(null),[match,setMatch]=useState(null),[events,setEvents]=useState([]),[err,setErr]=useState('');const call=async(p,o={})=>{const r=await fetch(API+p,{...o,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})}}),d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d};
const refresh=async()=>{if(!token)return;const m=await call('/me');setUser(m.user);setClub(m.club);if(m.user.clubId){setPlayers((await call('/players')).players);setLeagues((await call('/leagues')).leagues)}};
useEffect(()=>{refresh().catch(()=>{localStorage.removeItem('sklToken');setToken('')})},[token]);
if(!token)return <Auth onLogin={t=>{localStorage.sklToken=t;setToken(t)}}/>;
return <div className="app"><header><b>SKL27</b><span>{user?.displayName}</span><button onClick={()=>{localStorage.removeItem('sklToken');setToken('')}}>Logout</button></header><nav>{['home','squad','league'].map(x=><button className={screen===x?'active':''} onClick={()=>setScreen(x)}>{x}</button>)}</nav>{err&&<div className="error">{err}<button onClick={()=>setErr('')}>×</button></div>}{screen==='home'&&<Home club={club} onCreate={async name=>{try{const d=await call('/clubs',{method:'POST',body:JSON.stringify({name})});setClub(d.club);await refresh()}catch(e){setErr(e.message)}}}/>} {screen==='squad'&&<Squad players={players}/>} {screen==='league'&&<League leagues={leagues} club={club} call={call} onLeague={async id=>{try{const d=await call('/leagues/'+id);setLeague(d);setScreen('matchday')}catch(e){setErr(e.message)}}}/>} {screen==='matchday'&&league&&<Matchday data={league} call={call} onMatch={m=>{setMatch(m);setScreen('match')}}/>}{screen==='match'&&match&&<Match matchId={match.id} call={call}/>}</div>}
function Auth({onLogin}){const [mode,setMode]=useState('login'),[u,setU]=useState(''),[p,setP]=useState(''),[name,setName]=useState(''),[e,setE]=useState('');return <main className="center"><section className="card auth"><h1>Super Kings League 27</h1><p>Persistent 5v5 football management.</p>{mode==='signup'&&<input placeholder="Display name" value={name} onChange={e=>setName(e.target.value)}/>}<input placeholder="Username" value={u} onChange={e=>setU(e.target.value)}/><input type="password" placeholder="Password (6+ chars)" value={p} onChange={e=>setP(e.target.value)}/>{e&&<div className="error">{e}</div>}<button className="primary" onClick={async()=>{try{const d=await fetch(API+'/auth/'+mode,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(mode==='login'?{username:u,password:p}:{username:u,password:p,displayName:name})});const x=await d.json();if(!d.ok)throw Error(x.error);onLogin(x.token)}catch(x){setE(x.message)}}}>{mode==='login'?'Login':'Create account'}</button><button onClick={()=>setMode(mode==='login'?'signup':'login')}>{mode==='login'?'Create account':'Back to login'}</button></section></main>}
function Home({club,onCreate}){const [name,setName]=useState('');return <main><section className="hero"><h1>{club?club.name:'Create your club'}</h1><p>{club?'Your club is connected to the persistent SKL27 server.':'Start a real persistent football-management save.'}</p>{!club&&<><input placeholder="Club name" value={name} onChange={e=>setName(e.target.value)}/><button className="primary" onClick={()=>onCreate(name)}>Create Club</button></>}</section></main>}
function Squad({players}){return <main><h2>Squad</h2><div className="grid">{players.map(p=><article className="card"><b>{p.name}</b><span>{p.position} · OVR {p.overall}</span><span>Fitness {p.fitness} · Form {p.form}</span></article>)}</div></main>}
function League({leagues,club,call,onLeague}){const [name,setName]=useState('Friends League');const [invite,setInvite]=useState('');return <main><h2>Friends Leagues</h2>{leagues.map(l=><article className="card row"><div><b>{l.name}</b><span>Season {l.currentSeason} · {l.status}</span></div><button onClick={()=>onLeague(l.id)}>Open</button><button onClick={async()=>{try{await call('/leagues/start',{method:'POST',body:JSON.stringify({leagueId:l.id})});onLeague(l.id)}catch(e){alert(e.message)}}}>Start season</button><input placeholder="username to invite" value={invite} onChange={e=>setInvite(e.target.value)}/><button onClick={async()=>{try{await call('/leagues/invite',{method:'POST',body:JSON.stringify({leagueId:l.id,username:invite})});setInvite('')}catch(e){alert(e.message)}}}>Invite</button></article>)}<section className="card"><input value={name} onChange={e=>setName(e.target.value)}/><button className="primary" onClick={async()=>{try{await call('/leagues',{method:'POST',body:JSON.stringify({name})});location.reload()}catch(e){alert(e.message)}}}>Create Friends League</button></section></main>}
function Matchday({data,call,onMatch}){return <main><h2>{data.league.name} · Matchday {data.league.currentMatchday}</h2><div className="grid">{data.fixtures.map(f=><article className="card"><b>{f.home.name} vs {f.away.name}</b><span>{f.status}</span>{f.homeScore!==null&&<strong>{f.homeScore} - {f.awayScore}</strong>}{f.status!=='played'&&<button className="primary" onClick={async()=>{try{const d=await call('/matches/start',{method:'POST',body:JSON.stringify({fixtureId:f.id})});onMatch(d.match)}catch(e){alert(e.message)}}}>Watch / Start</button>}</article>)}</div><h3>Standings</h3><Table rows={data.standings}/></main>}
function Table({rows}){return <div className="table">{rows.map((r,i)=><div className="tr"><b>{i+1}. {r.name}</b><span>{r.played} GP</span><span>{r.wins}-{r.draws}-{r.losses}</span><strong>{r.points} pts</strong></div>)}</div>}
function Match({matchId,call}){const [d,setD]=useState(null);useEffect(()=>{let alive=true;const go=async()=>{try{const x=await call('/matches/'+matchId);if(alive)setD(x)}catch{}};go();const t=setInterval(go,1000);return()=>{alive=false;clearInterval(t)}},[matchId]);if(!d)return <main><div className="card">Loading match…</div></main>;return <main><section className="score card"><small>{d.match.phase}</small><h1>{d.home.name} {d.match.homeScore} — {d.match.awayScore} {d.away.name}</h1><strong>{d.match.minute}'</strong><p>Possession {d.match.possession}% — {100-d.match.possession}%</p></section><section className="timeline">{d.events.slice().reverse().map(e=><article className="card"><b>{e.minute}'</b> {e.text}</article>)}</section></main>}
ReactDOM.createRoot(document.getElementById('root')).render(<App/>);